[build]
builder = "nixpacks"

[deploy]
startCommand = "node -e \"const {execSync} = require('child_process'); execSync('npx prisma generate', {stdio:'inherit'}); \" && next start"
healthcheckPath = "/api/auth/me"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
